# Generated by Django 3.1.3 on 2021-04-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_num', models.CharField(blank=True, max_length=12, unique=True)),
                ('order_price', models.FloatField(blank=True, null=True)),
                ('issued_all', models.BooleanField(default=False)),
                ('issued_partial', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sales.customers')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothe_num', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('issued_num', models.IntegerField(default=0)),
                ('pending_num', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('total_price', models.FloatField(blank=True)),
                ('order_header', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sales.ordersheader')),
            ],
        ),
    ]
