# Generated by Django 3.2.10 on 2022-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdetail',
            name='inventory_num',
            field=models.IntegerField(default=0),
        ),
    ]
