# Generated by Django 3.1.3 on 2021-02-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=11)),
                ('wechat', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userinfo')),
            ],
        ),
    ]
